[package]
name = "flick"
version = "0.0.1"
edition = "2024"

[dependencies]
block2 = "0.6"
dirs = "7.0.0"
global-hotkey = "0.7"
nucleo-matcher = "0.3"
objc2 = "0.6"
objc2-app-kit = { version = "0.3", features = ["objc2-quartz-core"] }
objc2-foundation = "0.3"
objc2-quartz-core = "0.3"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.8"
